package uk.co.clarob.primes;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Generated by Spring initializr just to make sure application loads.
 */
@SpringBootTest
class PrimesApplicationTests
{
    @Test
    void contextLoads()
    {
    }
}
